apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xdso2eyim-nodejs 
  janus-idp.io/tekton: xdso2eyim-nodejs
  backstage.io/kubernetes-id: xdso2eyim-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xdso2eyim-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml